User auth (#1)
* some refactoring in the network layer

* init migrating to apollo

* auth with Apollo research paused

* resolver. compiling

* TypeError: config.accountsServer.getServices is not a function

* works, now ttry to refactor.

* compiling, but not working.

* uploadable to aws

* hello world on AWS

* reset

* basic bookstore on localhost

* local mongo working

* Reading users from a mongoDB remove server

* process env